version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install Java 17
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            java -version
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Linting
          command: |
            . venv/bin/activate
            flake8 .
      - run:
          name: Run tests with coverage report
          command: |
            . venv/bin/activate
            pytest --cov=app --cov-report=xml --cov-report=term
      - run:
          name: Install SonarCloud scanner
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
            unzip sonar-scanner-cli-4.7.0.2747-linux.zip
            echo 'export PATH=$PATH:./sonar-scanner-4.7.0.2747-linux/bin' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Run SonarCloud analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=tu_proyecto \
              -Dsonar.organization=tu_organizacion \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN
      - run:
          name: Run Snyk Security Scan
          command: |
            . venv/bin/activate
            npm install -g snyk
            snyk auth $SNYK_TOKEN
            snyk test || true

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
