version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Install Java
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
      - run:
          name: Install Python
          command: |
            sudo apt-get install -y python3 python3-pip python3-venv
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Linting
          command: |
            . venv/bin/activate
            flake8 .
      - run:
          name: Run tests with coverage
          command: |
            . venv/bin/activate
            pytest --cov=app --cov-report=xml --cov-report=term
      - run:
          name: Run SonarCloud Scanner
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
            unzip sonar-scanner-cli-5.0.1.3006-linux.zip
            ./sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner \
              -Dsonar.projectKey=ThomasAlbertoLombardo_ci-cd-python-app \
              -Dsonar.organization=thomasalbertolombardo \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${SONAR_TOKEN} \
              -X
      - run:
          name: Run Snyk test
          command: |
            . venv/bin/activate
            npm install snyk --save-dev
            ./node_modules/.bin/snyk auth $SNYK_TOKEN
            ./node_modules/.bin/snyk test --all-projects --json > snyk_report.json || true
      - store_artifacts:
          path: snyk_report.json  # Almacenar el reporte como artefacto
          destination: snyk_report  # Nombre del directorio donde se almacenará

workflows:
  build-test:
    jobs:
      - build-and-test
