version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest-cov  # Asegúrate de que pytest-cov esté instalado
      - run:
          name: Run Linting
          command: |
            . venv/bin/activate
            flake8 .
      - run:
          name: Run tests with coverage report
          command: |
            . venv/bin/activate
            pytest --cov=app --cov-report=xml --cov-report=term
      - run:
          name: Run SonarCloud analysis
          command: |
            . venv/bin/activate
            sonar-scanner \
              -Dsonar.projectKey=tu_proyecto \
              -Dsonar.organization=tu_organizacion \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN 
      - run:
          name: Run Snyk Security Scan
          command: |
            . venv/bin/activate
            npm install -g snyk
            snyk auth $SNYK_TOKEN
            snyk test

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test