version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Install Python
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip python3-venv
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Linting
          command: |
            . venv/bin/activate
            flake8 .
      - run:
          name: Run tests with coverage
          command: |
            . venv/bin/activate
            pytest --cov=app --cov-report=xml --cov-report=term
      - run:
          name: Run SonarCloud analysis
          command: |
            . venv/bin/activate
            sonar-scanner \
              -Dsonar.projectKey=ThomasAlbertoLombardo_ci-cd-python-app \
              -Dsonar.organization=thomasalbertolombardo \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${SONAR_TOKEN} 
      - run:
          name: Run Snyk test
          command: |
            . venv/bin/activate
            snyk test --all-projects --json > snyk_report.json || true

workflows:
  build-test:
    jobs:
      - build-and-test

